export const senaraiGuruAsal = [
  { id: 1, nama: "EN. ABDUL KODIR BIN SHAHARUDIN" },
  { id: 2, nama: "PN. NORASYIKIN BINTI SABTU" },
  { id: 3, nama: "PN. THOHARAH BINTI ABDULLAH" },
  { id: 4, nama: "CIK NOOR HAPIZAH BINTI MAMAT" },
  { id: 5, nama: "PN. AZIZAH BINTI MUDA" },
  { id: 6, nama: "PN. NUR TASNIM BINTI ABDUL MALIK" },
  { id: 7, nama: "PN. NORAZLINA BINTI RAMLY" },
  { id: 8, nama: "CIK NURUL AFIQAH BINTI AHMAD TARMEZE" },
  { id: 9, nama: "PN. SUHANA BINTI YUSOF" },
  { id: 10, nama: "PN. FATHENNABILA BINTI MAT LAZIM" },
  { id: 11, nama: "PN. MAIMUN BINTI HUSSIN" },
  { id: 12, nama: "CIK NURFATIHAQ BINTI MUSTAFA" },
  { id: 13, nama: "PN. NURUL HAFIZZAH BINTI ZAM" },
  { id: 14, nama: "PN. SHARIFAH ASMA FASYIHAQ BINTI SAID OMAR" },
  { id: 15, nama: "PN. ROHANI BINTI AHMAD" },
  { id: 16, nama: "PN. 'ARIFAH BINTI SABRI" },
  { id: 17, nama: "PN. HUSNA BINTI SUIT" },
  { id: 18, nama: "PN. NOR'ADILAH BINTI MOHD RASHIN" },
  { id: 19, nama: "PN. ASNITAH BINTI KUSAIN" },
  { id: 20, nama: "PN. NORSHAM AZIRA BINTI ABD SAMAT" },
  { id: 21, nama: "PN. YASWINI A/P KANAGASABAI" },
  { id: 22, nama: "PN. SARIMAH BINTI SA'AYA" },
  { id: 23, nama: "EN. SYAHRIZAN BIN IBRAHIM" },
  { id: 24, nama: "EN. MOHD FARIS FARIMAN BIN RAZALI" },
  { id: 25, nama: "PN. NOORHAMIZA BINTI ABD HAMED" },
  { id: 26, nama: "PN. SHREENPAL KAUR SANDHU A/P JIGEER SINGH" },
  { id: 27, nama: "CIK NURIN INSYIRAH BINTI RUSDI" },
  { id: 28, nama: "EN. AHMAD ZUBAIR BIN SOFIAN" },
  { id: 29, nama: "PN. RATIGA A/P DADAYAN" },
  { id: 30, nama: "PN. NOOR SHARINA BINTI MOHAMMAD SHAH" }
];

export const KADAR_BAYARAN = 53;
